### ISSUE TITLE
Pain points

### ISSUE THREAD

**Issue by mkasztelnik** [cyfronet-fid/marketplace#1020]
In the scope of this issue, we should try to identify and describe the application pain point. This will help us to find the places to refactor first:

  * [x] #1127, #1153 filters specs are fragile and replicated (testing all filters instead of filter type)
  * [x] #1035 `project_items/:id` -> `projects/:project_id/items/:iid`
  * [x] #1081 filter counters defined in `Service::Filterable` has part of the logic defined in `Service::Searchable`
  * [ ] #1236 Order Attributes cannot be reused by another offer - proposition is to use DB model to store attribute, use single table inheritance for a different attribute type, configuration stored in `jsonb` and to use `store_accessor` to defined fields for a specific attribute type. The open question is how to connect attribute with category and how to add search capability.
  * [ ] Jira client has many reasons to change right now
  * [x] #1042 Order views have code repetition - use partials to store reusable elements
  * [x] #1042 While the project is selected during the ordering process `json` is sent from the server and projet details are rendered using JS. We can simplify this and reuse existing views by returning rendered view attached to the page DOM
  * [x] #1043 Use `Project::Authorize` concern in each controller located in `/project/:project_id/something`
  * [x] #962 Remove affiliation model 
  * [ ] #1237 JIRA error handling is almost non existent - all potential errors have to be caught and handled in an appropriate manner
  * [ ] #1238 (Refactoring / Feature, but it can be done while refactoring JIRA) Issues can be deleted in JIRA, WebHook should handle those events and set `ProjectItem` `issues_status` to `:jira_deleted`
  * [ ] #1238 (Refactoring / Feature / Bug?) After last release / deployment there appeared `ProjectItem`s which have `issue_status` set to `:jira_deleted`. As far as I know we do not handle this status in any shape and form.
  * [x] #1038 `ProjectController.create` shares some logic with `Project::Create` and generally its content could be moved to the service
  * [x] ~~I have some problems with the way services call jobs and then jobs call services.
We either need a clear guide which services are called by jobs, or call jobs directly, or something else @mkasztelnik - Some guidelines? One good example could be `Project::Create` -> `Project::ProjectRegisterJob` -> `Project::Register`, where method body contains only call to the next service.~~
  * [x] #1033 change jQery to js on backoffice/services/form  
  * [ ]  comment deleted error handling 
  * [x] #1046 JS unittests for stimulous
  * [ ]  Vouchers cleanup
  * [x] #1342 Template unification for all modals

## Minor
  * [x] #1037 Typos: `flash[:allert] = "Project cannot be archived"`
  * ~~[ ] `redirect_to [:backoffice, @service]` in some cases `redirect_to` is called with `[]` and sometimes not, we can fix it, to be uniform~~

**Comment by michal-szostak** [comment]
* [ ] JIRA error handling is almost non existent - all potential errors have to be caught and handled in an appropriate manner

* [ ] (Refactoring / Feature, but it can be done while refactoring JIRA) Issues can be deleted in JIRA, WebHook should handle those events and set `ProjectItem` `issues_status` to `:jira_deleted`

* [ ] (Refactoring / Feature / Bug?) After last release / deployment there appeared `ProjectItem`s which have `issue_status` set to `:jira_deleted`. As far as I know we do not handle this status in any shape and form.

* [ ] `ProjectController.create` shares some logic with `Project::Create` and generally its content could be moved to the service

* [ ] I have some problems with the way services call jobs and then jobs call services.
We either need a clear guide which services are called by jobs, or call jobs directly, or something else @mkasztelnik - Some guidelines? One good example could be `Project::Create` -> `Project::ProjectRegisterJob` -> `Project::Register`, where method body contains only call to the next service.

## Minor
* [ ] Typos: `flash[:allert] = "Project cannot be archived"`

* [ ] `redirect_to [:backoffice, @service]` in some cases `redirect_to` is called with `[]` and sometimes not, we can fix it, to be uniform

**Comment by martaswiatkowska** [comment]
- [ ]  change jQery to js on backoffice/services/form
- [ ]  comment deleted error handling

**Comment by bwilk** [comment]
https://shime.sh/testing-stimulus

**Comment by michal-szostak** [comment]
* [ ] JS unittests for stimulous

**Comment by bwilk** [comment]
* [ ] Vouchers

**Comment by bwilk** [comment]
#1082 describes previously established tasks connected with implementation of attributes

**Comment by martaswiatkowska** [comment]
"Order views have code repetition - use partials to store reusable elements" isn't done in https://github.com/cyfronet-fid/marketplace/pull/1042/files ??

**Comment by mkasztelnik** [comment]
@martaswiatkowska you are right this is done in the scope of #1042 - status updated - thx!
