### ISSUE TITLE
Whitelabel

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/marketplace#1328]
User Story:

- [ ] The User can see and use the footer according to the proposed design.
- [ ] The User can read Privacy Policy which is suited in the visible place on the page
- [ ] The User can place an order and receive proper feedback about the order
