### ISSUE TITLE
Whitelabel - stage 1 - cleanup and generalization

### ISSUE THREAD

**Issue by mkasztelnik** [cyfronet-fid/marketplace#1336]
# Whitelabel - what it is?
Marketplace UI right now is customized for EOSC. In the scope of Whitelabel tasks activities, we would like to introduce some kind of customization, which allows deploying marketplace for other organizations. Since this is a complicated task we will split it into several steps. Bellow first stage is described. 

# Stage 1 - cleanup and generalization
To get more knowledge about the Whitelabel difficulty level at the beginning we want to clean up views and externalize "components". By "component" I mean set of view which should be simple for customization. For now, we want to focus our activities on the following views: home page, header, footer.

In the description below I don't mention CSS customization. This is a separate activity led by @abacz.

## TODOs
  * [x] #1343 externalize homepage sections into separate partials
  * [x] #1341 move categories and branch of sciences logos into DB using active storage. 
  * [x] #1348 refactor partials in service search view and reuse them in the backoffice
  * [x] #1356 refactor rendering sidebar information
  * [x] #1344 read rails documentation and check if we can customize views (this https://apidock.com/rails/ActionController/Base/prepend_view_path can be a start, but maybe there are more possibilities). This mechanism can be used to customize the footer and header.
  * ~~#1344 (follow up from the previous bullet) check how [high voltage](https://github.com/thoughtbot/high_voltage) behave when additional view paths are defined. Is it possible to generate new pages there, remove pages defined in the main branch but not used in customization?~~ High voltage was used only in static help - it was removed after help was moved into DB

## Extras / to consider:
  * [x] ~ #1370 Move `Learn more` section into DB (with more generic name - take a look at next point for rationale)
  * [x] ~ #1370 Consider creating something like `information row` with title and set of elements. Something like this can be used to model `Learn more` and `Use cases` sections.
  * [x] ~ #1353 Check if we can use [trix](https://trix-editor.org/) and [active text](https://edgeguides.rubyonrails.org/action_text_overview.html) can be used to customize sections like homepage main section, all placeholders (e.g. information steps during ordering, empty projects list placeholder, empty project placeholder, etc.)
  * ~~ ~ If additional views path customization will not be enough, consider sub repositories. Take a look at the example prepared for this purpose by @bwilk https://github.com/bwilk/submodules_test~~
  * [x] ~ #1353 Consider moving help into DB (e.g. fields: name, description as active text object)

# Next steps
This sprint should give us knowledge about the amount of work needed to introduce further customization. Some of the techniques validated here can be further reused or even more generalized.

**Comment by mkasztelnik** [comment]
All elements mentioned in this task are already done
