### ISSUE TITLE
Recommendation System POC

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#1756]
The scope of this *epic* is creation of basic POC recommendation system.
The POC does not have to return any sane recommendations (could return results directly from `elasticsearch`)

context:
https://docs.cyfronet.pl/display/FID/Edited%3A+First+prototype+of+the+recommendation+system

This Epic consists of:

- [x] Define and implement API #1757 
  - [x] Define API and implement endpoints with validations for recommendations and probes @JanKapala 
  - [x] Define API and implement endpoint with validations for db injection @JanKapala   
- [x] Create serializer for MP database #1758
- [x] Define probes #1760 @JanKapala 
- [x] Choose DB backend for storing MP database dump #1759 @JanKapala
