### ISSUE TITLE
Recommendation System

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#1783]
Problem analysis along with all comments and additional context is available here:
https://docs.cyfronet.pl/display/FID/First+prototype+of+the+recommendation+system

Issues in epic:

* [x] Implement Probes for recommendation system #1782
* [ ] Configure Github actions CI / CD cyfronet-fid/recommender-system#3 (moved to backlog)
* [x] Collapse user actions into tree cyfronet-fid/recommender-system#4
* [x] Store SARS data in database cyfronet-fid/recommender-system#5
* [ ] Research authentication options cyfronet-fid/recommender-system#6 (moved to backlog)
* [x] Configure Dockerfile and docker-compose cyfronet-fid/recommender-system#7
* [x] Store database dump in mongo DB, create DAO abstraction cyfronet-fid/recommender-system#8
* [x] Expose functionality in API endpoints cyfronet-fid/recommender-system#9
