### ISSUE TITLE
Improve Marketplace's SQA

### ISSUE THREAD

**Issue by Michal-Kolomanski** [cyfronet-fid/marketplace#3365]
Person in charge: @goreck888 

Links:
https://docs.google.com/spreadsheets/d/1BhSce-sCqu9HWwub2xuSk84bUC2xL6ouOrTTjCBOIGk/edit?gid=68832361#gid=68832361
Read emails: especially: [EOSC Beyond] SQA - action required for your code repository marketplace

Scope:
- create smaller tickets on demand
- communicate with Joao Pina, John Shepherdson (beyond slack/email) if needed
- [ ] Get a bronze badge 
- [ ] Get a silver badge 
- [ ] Get a gold badge

**Comment by Michal-Kolomanski** [comment]
blocked by: contact email
