### ISSUE TITLE
Adjust to new Provider Component's changes

### ISSUE THREAD

**Issue by Michal-Kolomanski** [cyfronet-fid/marketplace#3366]
Person in charge: @goreck888 

```
Changes:
	* IDs:
		* migration to "{pid_prefix}/{suffix}", where suffix consists of "catalogueId" and a "random_alphanumeric" ({prefix}/{catalogueId}.{random 6 digit alphanumeric})
		  (eg. Provider eosc.openaire -> 21.T15999/eosc.nsBy5v)
		* ID-related API calls change from /{id} to {prefix}/{suffix}
	* New fields:
		* Bundles:
			* boolean draft
			* String auditState

```

Links:
https://integration.providers.sandbox.eosc-beyond.eu/openapi - their API still doesn't work. Inform them about it until its working

Scope:
- create smaller tickets on demand
- communicate with PC if needed
- [ ] Research how big of a deal those changes are for us
- [ ] Plan our work, write tickets
- [ ] Adjust Marketplace if needed
- [ ] Make sure that our MP sandbox is integrated with the equivalent env of the PC 
- [ ] Make sure that we are integrated with the queue https://integration.providers.sandbox.eosc-beyond.eu/ and that it works.
