### ISSUE TITLE
Scientific discipline in the ordering form

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#589]
Requirement from the EOSC-hub partners

to accomplish a request we received from the EC through our project officer, we need to extend the current Marketplace check-out form with an additional parameter where the customer can select his/her scientific discipline of interest.
The new field in the form should be mandatory.
I would suggest to use the disciplines in the second level category from https://wiki.egi.eu/wiki/Scientific_Disciplines
but, feel free to propose any better/alternative solutions.

-----------------------------
add new element in the USAGE section in the 2nd step of the ordering proces:
Scientific discipline (TODO: podpowiedź)

In the app we already have a researchArea model which can be used for that purpose. in order to meet the requirements. to the model we need to add hierarchical structure.

under this we will need to add some technical tasks:
- [x] #439 implement hierarchy in the model and migration (for current relations between services and branches of science) 
- [x] populate with proper content to the branch of science there
- [x] #637 adding branch of science field to the order form (check if this should be select of multi select)
- [x] #637 show branch of science in the Project item view
- [x] #637 add branch of science field from the project item to the MP-JIRA integration

**Comment by roksanaer** [comment]
task is simple (we need to add one more attribute to the 2nd step configuration Usage part of the form), the only thing we need to establish is the GU interface of this attribute. @abacz  can you suggest something? list is long so I see two options
1. search like input field with a link under pointing to the page given by Diego with a list of possible scientific disciplines and info, that the user should look at the second level of categorisation. when the user starts filling in the field, possible options to choose from appear (same like scientific branch field in Bazaar 2.0)
2. select to choose from

**Comment by roksanaer** [comment]
3 technical possible solutions:
config file
enum
element of the model

**Comment by mkasztelnik** [comment]
@roksanaer can we use values from `ResearchArea` records and allow a user to choose only second (third, fourth, ..., but not first) level?

**Comment by roksanaer** [comment]
@mkasztelnik if i understand your idea correctly then not. research area for the service can be 'multidisciplinary' - this cannot be claimed in the order form. user should be able to choose any value from the 2 levels hierarchy

**Comment by roksanaer** [comment]
after consultation with Diego:
- we are starting with a select
- user should choose from the second level only

**Comment by roksanaer** [comment]
adequate field was added to jira ticket template: 

CP-ScientificDiscipline ID: 10706

**Comment by mkasztelnik** [comment]
[Choises.js](https://github.com/jshjohnson/Choices) will be used to show nice grouped multi-select. This library was already accepted by @abacz. In the future, we can use it to create a more user-friendly way to manage service tags.
