### ISSUE TITLE
Apply the new design of service access paths

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#964]
**Is your feature request related to a problem? Please describe.**
Experience in ordering services in the Marketplace showed that we need to make a redesign of their paths.

**Describe the solution you'd like**

***General info for all types of services***
- [x]  on the main page of the service in all types of services (normal, open_access and catalog) we leave only one button "Access the service", this button should always redirect to the zero or first step of the ordering procedure, but for each type of service it will look different - no log-in required
- [x] STEP 1: information step, available for each type of service offer, we show here general information about specific access type (normal, open access, catalogue will have different content here), - no login reguired  (detailed information is described below for each type)
- [x] STEP 0:  if service has more than one offer (>=2) we always show to the user the zero step where he/she has the possibility to choose one
- [x] STEP 2: parameters  of the service offer if exists - login required
- [x] STEP 3: summary of parameters and project selection option (required)
- ~~[ ] for all types of services after finishing the ordering procedure the user should be redirected to the project page (https://kcjh3g.axshare.com/#g=1&p=my_projects) and we should "highlight" the ordered service according to https://kcjh3g.axshare.com/#g=1&p=request_egi_cloud_-step-3-summary_before_send (click Proceed to Order to see)~~

***Normal type*** - STEP 1
- [x] on the top of this page we should add text which will inform the user about this type of service:

_The Service name_ can be ordered via EOSC marketplace **free of charge**. The service will be delivered once it is verified that the scientific affiliation (provided in the details of the underpinned project) entitles you to use it.  You will be notified by email about the service request status changes or can be tracked in project’s dashboard.
To find out more about Projects in EOSC Marketplace, please refer to our FAQ ( link to FAQ)

 To all that has offers : To gain access to the service, please select the offer that suits your needs best and add it to a project
- one button, named: Next

***Open access type*** - STEP 1
- [x] on the top of this page we should add text which will inform the user about this type of service

_The Service name_ is open to everyone, any user can reach the service. You can either directly **'Go to the service'**, where EOSC Portal will redirect you to the service website or what is highly recommended to add the service to your **'Project'**. It helps you to organise your services and orders into logical blocks related to your use case, gain EOSC experts support and easily access the selected service.  
To find out more about Projects in EOSC Marketplace, please refer to our FAQ ( link to FAQ)
- [x]  two buttons available: Open service website and Next

***Catalog type*** - STEP 1
- [x] on the top of this page we should add text which will inform the user about this type of service

_The Service name_ is accessible by external ordering. You can either directly **'Go to the service'**, where EOSC Portal will redirect you to the website and you can order the service or what is highly recommended to add the service to your **'Project'**. It helps you to organise your services and orders into logical blocks related to your use case, gain EOSC experts support and easily access the selected service.    
To find out more about Projects in EOSC Marketplace, please refer to our FAQ  ( link to FAQ)

- [x] two buttons available: Next and Order with provider

**Additional context**
![IMG_20191015_170908.jpg](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/fa707afb-93cf-438f-8aaf-3e38f60b4d41)

Connected axshare: https://kcjh3g.axshare.com/#g=1&p=service-detail_regular_service

**Comment by bwilk** [comment]
### TODO
  1. Catalogue type type "ordering"
      * [ ] Remove service type from service model
      * [ ] Change "normal" to "orderable" in the enum in service offer
      * [ ] Allow adding "catalogue" to a project (similar to "open access")
  1. Workflow
      * [ ] Introduce information step (1)
      * [ ] Remove authenticate on controller at the beginning of the ordering path 
      * [ ] Move project selection from (2) to (3)

**Comment by bwilk** [comment]
I have a general question with regard to TODO 1, box 2. How we should name three types of service offers. Currently we have:

```
 enum service_type: {
    normal: "normal",
    open_access: "open_access",
    catalog: "catalog"
  }
```
**normal** is unacceptable - what is this norm we are talking about? The meaning should be -orderable internally 
**catalog** is in fact orderable externally - the name does not say much about that

**Comment by agpul** [comment]
I propose not service_type but service_access:
1. Internal ordering
2. Open
3. External ordering or if you think that it doesn't say much about that maybe something like: provider-side ordering

@MinLidia maybe you have some better ideas:)

**Comment by MinLidia** [comment]
I would suggest to leave Service type ( as ordering has nothing with access) , can be misleading, but change the name as you proposed : 

1. Internal ordering
2. Open access 
3. External ordering 

What do you think? @agpul @roksanaer

**Comment by MinLidia** [comment]
I agree with Aga. We already proposed such solution on a service view with naming : service access., so we will have consistency

![Screenshot 2019-10-22 at 09.36.52.png](https://images.zenhubusercontent.com/5d774fae59191331a107c328/4a4facbc-c985-48fa-89f0-2918a2805575)

**Comment by mkasztelnik** [comment]
To have short and consist names I propose the following enum:

```ruby
enum access_type: [:orderable, :open, :external]
```

Of course on the view, We will have a more meaningful description of each type.

**Comment by martaswiatkowska** [comment]
Any conclusion? @agpul @roksanaer @MinLidia @mkasztelnik

**Comment by agpul** [comment]
I agree with Marek proposition, you are the code owners so it should be clear for you, we will adjust it in the front.

**Comment by mkasztelnik** [comment]
All changes described here are already in `master`
